# Generated by Django 3.2 on 2023-06-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='1234567890qwe', max_length=13),
        ),
    ]
