# Generated by Django 3.2 on 2023-07-10 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genretitle',
            name='genre',
            field=models.ForeignKey(help_text='Выберите жанр', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.genre', verbose_name='жанр'),
        ),
        migrations.AlterField(
            model_name='genretitle',
            name='title',
            field=models.ForeignKey(help_text='Выберите произведение', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.title', verbose_name='произведение'),
        ),
    ]
