# Generated by Django 3.2 on 2023-07-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, default='empty', help_text='Добавьте описание произведения', verbose_name='описание произведения'),
            preserve_default=False,
        ),
    ]
