# Generated by Django 3.2 on 2023-07-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230704_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='1fPzjLb1uceeb', max_length=13),
        ),
    ]
