# Generated by Django 3.2 on 2023-07-06 17:28

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Укажите название', max_length=256, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Укажите уникальный фрагмент URL-адреса', unique=True, verbose_name='Уникальный фрагмент URL-адреса'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Укажите название', max_length=256, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(help_text='Укажите уникальный фрагмент URL-адреса', unique=True, verbose_name='Уникальный фрагмент URL-адреса'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(db_index=True, help_text='Укажите год создания произведения', validators=[reviews.validators.validate_year], verbose_name='Год создания произведения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='c5JPqWbkNry5p', max_length=13),
        ),
    ]
