# Generated by Django 3.2 on 2023-07-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230706_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='lQD8LuX2vfmvV', max_length=13),
        ),
    ]
