# Generated by Django 3.2 on 2023-07-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='oLRU0AvCX0nkE', max_length=13),
        ),
    ]
